dist: trusty
sudo: required

addons:
  apt:
    packages:
    - texlive-full
    - imagemagick

before_install:
- wget http://mirrors.ctan.org/macros/latex/contrib/titlesec.zip && unzip titlesec.zip
- sudo rm -r /usr/share/texlive/texmf-dist/tex/latex/titlesec
- sudo mv titlesec /usr/share/texlive/texmf-dist/tex/latex/
- wget https://raw.githubusercontent.com/kmorel/UseLATEX/master/UseLATEX.cmake
- wget https://github.com/latex4ei/latex4ei-packages/archive/master.zip && unzip master.zip
- sudo mv latex4ei-packages-master/template-files/latex4ei /usr/share/texlive/texmf-dist/tex/latex/latex4ei
- sudo mktexlsr

install: true

script:
- pdflatex StochastischeSignalePraktikum.tex
- mkdir -p build
- cp UseLATEX.cmake build/UseLATEX
- cd build && cmake ..; make

notifications:
  email: false
